version: '2'
services:
    av-api:
        image: byuoitav/av-api:stage
        ports:
            - "8000:8000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
    pjlink-microservice:
        image: byuoitav/pjlink-microservice:stage
        ports:
            - "8005:8005"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PJLINK_PORT=$PJLINK_PORT
            - PJLINK_PASS=$PJLINK_PASS
        network_mode: "host"
        restart: always
        tty: true
    configuration-database-microservice:
        image: byuoitav/configuration-database-microservice:stage
        ports:
            - "8006:8006"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_USERNAME=$CONFIGURATION_DATABASE_USERNAME
            - CONFIGURATION_DATABASE_PASSWORD=$CONFIGURATION_DATABASE_PASSWORD
            - CONFIGURATION_DATABASE_HOST=$CONFIGURATION_DATABASE_HOST
            - CONFIGURATION_DATABASE_PORT=$CONFIGURATION_DATABASE_PORT
            - CONFIGURATION_DATABASE_NAME=$CONFIGURATION_DATABASE_NAME
        network_mode: "host"
        restart: always
        tty: true
    sony-control-microservice:
        image: byuoitav/sony-control-microservice:stage
        ports:
            - "8007:8007"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - SONY_TV_PSK=$SONY_TV_PSK
        network_mode: "host"
        restart: always
        tty: true
    london-audio-microservice:
        image: byuoitav/london-audio-microservice:stage
        ports:
            - "8009:8009"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    pulse-eight-neo-microservice:
        image: byuoitav/pulse-eight-neo-microservice:stage
        ports:
            - "8011:8011"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    kramer-microservice:
        image: byuoitav/kramer-microservice:stage
        ports:
            - "8014:8014"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    adcp-control-microservice:
        image: byuoitav/adcp-control-microservice:stage
        ports:
            - "8012:8012"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    touchpanel-ui-microservice:
        image: byuoitav/touchpanel-ui-microservice:stage
        ports:
            - "8888:8888"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - HELP_SLACKBOT_WEBHOOK=$HELP_SLACKBOT_WEBHOOK
            - UI_CONFIGURATION_ADDRESS=$UI_CONFIGURATION_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
    event-router-microservice:
        image: byuoitav/event-router-microservice:stage
        ports:
            - "7000:7000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_NODE_ADDRESSES=$EVENT_NODE_ADDRESSES
        network_mode: "host"
        restart: "always"
        tty: true
    event-translator-microservice:
        image: byuoitav/event-translator-microservice:stage
        ports:
            - "7002:7002"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
    device-monitoring-microservice:
        image: byuoitav/device-monitoring-microservice:stage
        ports:
            - "10000:10000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - DEVICE_PING_INTERVAL=$DEVICE_PING_INTERVAL
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
    shure-audio-microservice:
        image: byuoitav/shure-audio-microservice:stage
        ports:
            - "8013:8013"
        environment:
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PI_HOSTNAME=$PI_HOSTNAME
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
