version: '3'
services:
    av-api:
        build:
            context: .
            dockerfile: Dockerfile-development
        ports:
            - "8000:8000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - DEVELOPMENT_HOSTNAME=$DEVELOPMENT_HOSTNAME
        network_mode: "host"
        restart: always
    pjlink-microservice:
        build: 
            context: ../pjlink-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8005:8005"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PJLINK_PORT=$PJLINK_PORT
            - PJLINK_PASS=$PJLINK_PASS
        network_mode: "host"
        restart: always
    configuration-database-microservice:
        build: 
            context: ../configuration-database-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8006:8006"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_USERNAME=$CONFIGURATION_DATABASE_USERNAME
            - CONFIGURATION_DATABASE_PASSWORD=$CONFIGURATION_DATABASE_PASSWORD
            - CONFIGURATION_DATABASE_HOST=$CONFIGURATION_DATABASE_HOST
            - CONFIGURATION_DATABASE_PORT=$CONFIGURATION_DATABASE_PORT
            - CONFIGURATION_DATABASE_NAME=$CONFIGURATION_DATABASE_NAME
        network_mode: "host"
        restart: always
    sony-control-microservice:
        build: 
            context: ../sony-control-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8007:8007"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - SONY_TV_PSK=$SONY_TV_PSK
        network_mode: "host"
        restart: always
    london-audio-microservice:
        build: 
            context: ../london-audio-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8009:8009"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    pulse-eight-neo-microservice:
        build: 
            context: ../pulse-eight-neo-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8011:8011"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    adcp-control-microservice:
        build: 
            context: ../adcp-control-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8012:8012"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
    touchpanel-ui-microservice:
        build: 
            context: ../touchpanel-ui-microservice
            dockerfile: Dockerfile-development
        ports:
            - "8888:8888"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - HELP_SLACKBOT_WEBHOOK=$HELP_SLACKBOT_WEBHOOK
            - DEVELOPMENT_HOSTNAME=$DEVELOPMENT_HOSTNAME
        network_mode: "host"
        restart: always
    configuration-database-tool:
        build: 
            context: ../configuration-database-tool
            dockerfile: Dockerfile-development
        ports:
            - "9999:9999"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
        network_mode: "host"
        restart: always
    event-router-microservice:
        build: 
            context: ../event-router-microservice
            dockerfile: Dockerfile-development
        ports:
            - "7000:7000"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - PI_HOSTNAME=$PI_HOSTNAME
            - DEVELOPMENT_HOSTNAME=$DEVELOPMENT_HOSTNAME
        network_mode: "host"
        restart: always
    event-translator-microservice:
        build:
            context: ../event-translator-microservice
            dockerfile: Dockerfile-development 
        ports:
            - "7002:7002"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - DEVELOPMENT_HOSTNAME=$DEVELOPMENT_HOSTNAME
        network_mode: "host"
        restart: always
