swagger: '2.0'
info:
  title: Brigham Young University Audiovisual API
  description: Manage various AV systems across BYU campus with the BYU AV API
  version: "0.0.1"
host: api.byu.edu
schemes:
  - https
produces:
  - application/json
paths:
  /rooms:
    get:
      summary: All Rooms
      description: |
        The Rooms endpoint returns information about the various AV products
        offered across campus. The response includes the display name
        and other details about each product.
      tags:
        - Rooms
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /check/{building}/{room}/{system}:
    get:
      summary: All Rooms
      description: |
        The Rooms endpoint returns information about the various AV products
        offered across campus. The response includes the display name
        and other details about each product.
      parameters:
        - name: building
          in: path
          description: BYU building shortname (JKB)
          required: true
          type: string
          format: double
        - name: room
          in: path
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: system
          in: path
          description: Latitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Rooms
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
